In [43]:
import numpy as np

In [44]:
# A bunch of matracies of diffrent sizes, for testing the 3x3 matrix is used
b_0 = [1,2]
b_1 = [3,4]

R_0 = [6,2,1]
R_1 = [3,3,4]
R_3 = [4,2,2]

r_0 = [6,2,1,1]
r_1 = [3,3,4,2]
r_2 = [4,2,2,4]
r_3 = [1,1,1,1]

a_0 = [1,2,3,4,5]
a_1 = [6,7,8,9,10]
a_2 = [11,12,13,14,15]
a_3 = [16,17,18,19,20]
a_4 = [21,22,23,24,25]

c_0 = [1,2,3,4,5,6]
c_1 = [7,8,9,10,11,12]
c_2 = [13,14,15,16,17,18]
c_3 = [19,20,21,22,23,24]
c_4 = [25,26,27,28,29,30]
c_5 = [31,32,33,34,35,36]

d_0 = [1,2,3,4,5,6,7]
d_1 = [8,9,10,11,12,13,14]
d_2 = [15,16,17,18,19,20,21]
d_3 = [22,23,24,25,26,27,28]
d_4 = [29,30,31,32,33,34,35]
d_5 = [36,37,38,39,40,42,42]
d_6 = [43,44,45,46,47,48,49]

#A = np.array([b_0,b_1])
A = np.array([R_0,R_1,R_3])
#A = np.array([r_0,r_1,r_2,r_3])
#A = np.array([a_0,a_1,a_2,a_3,a_4])
#A = np.array([c_0,c_1,c_2,c_3,c_4,c_5])
#A = np.array([d_0,d_1,d_2,d_3,d_4,d_5,d_6])

print(A)

row = np.array([0,1,2])
order = ['x','y','z']


[[6 2 1]
 [3 3 4]
 [4 2 2]]


In [45]:
#find minor using standard notaotin
'''
def find_minor(col,row,A):

    col = col - 1
    row = row - 1

    B = np.delete(A,col, axis = 1)
    B = np.delete(B,row,axis = 0)

    return B
'''

'\ndef find_minor(col,row,A):\n\n    col = col - 1\n    row = row - 1\n\n    B = np.delete(A,col, axis = 1)\n    B = np.delete(B,row,axis = 0)\n\n    return B\n'

In [46]:
#get cofactor matrix of any nxn matrix A
'''
def cofactor_matrix(A):
        
    def find_minor(row,col,A):

        B = np.delete(A,col, axis = 1)
        B = np.delete(B,row,axis = 0)

        return B
        
    list_1 = []
    for a in range (len(A)):
        b = 0
        while b < len(A):

            co = (-1)**(a + b)

            minor = find_minor(a,b,A)
                    
            det_value = np.linalg.det(minor)
            b = b + 1
            list_1.append(det_value * co)
        
    list_2 = []
    c = 0
    d = len(A)
    while len(list_2) < len(A):

        arr_elem = list_1[c:d]
        list_2.append(arr_elem)

        c = d 
        d = d + len(A)
        
    return np.array(list_2)
        

a = cofactor_matrix(A)

print(a)
#print(b)

'''

'\ndef cofactor_matrix(A):\n\n    def find_minor(row,col,A):\n\n        B = np.delete(A,col, axis = 1)\n        B = np.delete(B,row,axis = 0)\n\n        return B\n\n    list_1 = []\n    for a in range (len(A)):\n        b = 0\n        while b < len(A):\n\n            co = (-1)**(a + b)\n\n            minor = find_minor(a,b,A)\n\n            det_value = np.linalg.det(minor)\n            b = b + 1\n            list_1.append(det_value * co)\n\n    list_2 = []\n    c = 0\n    d = len(A)\n    while len(list_2) < len(A):\n\n        arr_elem = list_1[c:d]\n        list_2.append(arr_elem)\n\n        c = d \n        d = d + len(A)\n\n    return np.array(list_2)\n\n\na = cofactor_matrix(A)\n\nprint(a)\n#print(b)\n\n'

In [ ]:
#nxn system of eq solver
# Using nested for - for loops

def nxn_system_solver(test_arr,row_vector,variable_order):

    def adjoint_matrix(A):
        
        def find_minor(col,row,A):

            B = np.delete(A,col, axis = 1)
            B = np.delete(B,row,axis = 0)

            return B
        
        list_1 = []
        for a in range (len(A)):

            for b in range (len(A)):

                co = (-1)**(a + b)

                minor = find_minor(a,b,A)
                    
                det_value = np.linalg.det(minor)

                list_1.append(det_value * co)
        
        list_2 = []
        c = 0
        d = len(A)
        while len(list_2) < len(A):

            arr_elem = list_1[c:d]
            list_2.append(arr_elem)

            c = d 
            d = d + len(A)
        
        return np.array(list_2)
    
    def inverse_matrix(A):

        det_value = np.linalg.det(A)

        inverse = adjoint_matrix(A)

        matrix = inverse/det_value

        return matrix
    
    def sqaure_row_nxn(test_arr,row_vector):
        
        list_0 = np.array([0] * len(row_vector))

        for a in range (len(row_vector)):

            list_1 = []
            for b in range (len(row_vector)):

                value = row_vector[a]*test_arr[b,a]
                list_1.append(value)

            list_0 = np.column_stack((list_0,list_1))
            list_final = np.delete(list_0, 0, axis = 1)

        list_2 = []

        for c in range (len(row_vector)):
                
            value = np.sum(list_final[c])
            list_2.append(value)
            
        return np.array(list_2)
    
    invese = inverse_matrix(test_arr)

    solution = sqaure_row_nxn(invese,row_vector)

    return solution , variable_order


In [48]:
solution, var_order = nxn_system_solver(A,row,order)
print(var_order)
print(solution)

['x', 'y', 'z']
[  4. -17.  10.]
